name: Ostium
title: Магазин Ostium
org: Ostium

profiles:
  development:
    base_url: http://localhost:4242
    minify: false
    disqus_developer: true
    dev: true
    deploy:
      dummy:
  production:
    base_url: http://ostiumlab.ru
    minify: true
