name: Ostium
title: Магазин Ostium
org: Ostium

profiles:
  production:
    minify: true
    base_url: http://cybernetlab.github.io/ostiumlab
    deploy:
      host: github_pages
  development:
    base_url: http://localhost:4242
    minify: false
    disqus_developer: true
    dev: true
    deploy:
      dummy:
